### ISSUE TITLE
MQTT_TOPIC

### ISSUE THREAD

**Issue by gr1g4** [YogaSakti/CoronaNotifier#3]
Bang, MQTT_TOPIC nya di isi apa?
ane kaga tahu sama sekali tentang mqtt, baru aja searching, malah keluar nya I.O.T

**Comment by YogaSakti** [comment]
topic yaitu berupa UTF-8 string yang perannya hampir sama seperti topik pada chat hanya saja lebih sederhana dan berfungsi sebagai filter untuk broker dalam mengirimkan pesan ke tiap klien yang terhubung atau dengan kata lain topic adalah kanal bagi klien untuk subscribe.

**Comment by YogaSakti** [comment]
contoh:
MQTT_TOPIC=Bot/WA/Corona
atau 
MQTT_TOPIC=robotWA
