### ISSUE TITLE
background running

### ISSUE THREAD

**Issue by ikkeh69** [YogaSakti/CoronaNotifier#5]
udah berhasil scan qr. terus mau run as service
`node CoronaService\corona.js`
tapi mentok di 
> Mqtt topic [robotWA] 

apa itu normal?
soalnya begitu tutup terminal, service berhenti

**Comment by YogaSakti** [comment]
![image](https://user-images.githubusercontent.com/24309806/78152137-9e060380-7463-11ea-8bcd-8d49f15bffd2.png)

corona.js harus running terus, soalnya dia checking data tiap 10 menit sekali.

buat running background pake PM2 atau pake screen di linux

**Comment by ikkeh69** [comment]
bener juga. makasih sarannya
