### ISSUE TITLE
stuck di qr code

### ISSUE THREAD

**Issue by ikkeh69** [YogaSakti/CoronaNotifier#9]
kenapa ya pas udah sampai di qr code, terus di scan dan di hpkatanya berhasil. tapi di server cuma stuck di Please Scan QR with app!

**Comment by Fahrineey546** [comment]
Update whatsapp-web.js ke last

**Comment by Fahrineey546** [comment]
> kenapa ya pas udah sampai di qr code, terus di scan dan di hpkatanya berhasil. tapi di server cuma stuck di Please Scan QR with app!

Update whatsapp-web.js ke last

**Comment by ikkeh69** [comment]
caranya gimana gan? soalnya ane cuma bisa ngikut yang ada di readme

**Comment by ikkeh69** [comment]
udah ane update wa-web.js nya. udah sukses juga kehubung. tapi pas neripa pesan error

`(node:1058) UnhandledPromiseRejectionWarning: ReferenceError: keyword is not defined
    at Client.client.on (/root/CoronaNotifier/index.js:110:26)
    at Client.emit (events.js:198:13)
    at page.exposeFunction.msg (/root/CoronaNotifier/node_modules/whatsapp-web.js/src/Client.js:207:18)
    at Page._onBindingCalled (/root/CoronaNotifier/node_modules/puppeteer/lib/Page.js:408:62)
    at CDPSession.Page.client.on (/root/CoronaNotifier/node_modules/puppeteer/lib/Page.js:126:60)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onMessage (/root/CoronaNotifier/node_modules/puppeteer/lib/Connection.js:166:18)
    at Connection._onMessage (/root/CoronaNotifier/node_modules/puppeteer/lib/Connection.js:83:25)
    at WebSocketTransport._ws.addEventListener (/root/CoronaNotifier/node_modules/puppeteer/lib/WebSocketTransport.js:25:32)
    at WebSocket.onMessage (/root/CoronaNotifier/node_modules/puppeteer/node_modules/ws/lib/event-target.js:125:16)
(node:1058) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1058) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

itu kenapa ya?

**Comment by Fahrineey546** [comment]
> udah ane update wa-web.js nya. udah sukses juga kehubung. tapi pas neripa pesan error
> 
> `(node:1058) UnhandledPromiseRejectionWarning: ReferenceError: keyword is not defined at Client.client.on (/root/CoronaNotifier/index.js:110:26) at Client.emit (events.js:198:13) at page.exposeFunction.msg (/root/CoronaNotifier/node_modules/whatsapp-web.js/src/Client.js:207:18) at Page._onBindingCalled (/root/CoronaNotifier/node_modules/puppeteer/lib/Page.js:408:62) at CDPSession.Page.client.on (/root/CoronaNotifier/node_modules/puppeteer/lib/Page.js:126:60) at CDPSession.emit (events.js:198:13) at CDPSession._onMessage (/root/CoronaNotifier/node_modules/puppeteer/lib/Connection.js:166:18) at Connection._onMessage (/root/CoronaNotifier/node_modules/puppeteer/lib/Connection.js:83:25) at WebSocketTransport._ws.addEventListener (/root/CoronaNotifier/node_modules/puppeteer/lib/WebSocketTransport.js:25:32) at WebSocket.onMessage (/root/CoronaNotifier/node_modules/puppeteer/node_modules/ws/lib/event-target.js:125:16) (node:1058) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:1058) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
> 
> itu kenapa ya?

Buka file Index.js masuk ke line 110 hapus (s) jadii keybord saja. Nanti mau di Update sama mas Yoga

**Comment by ikkeh69** [comment]
@Fahrineey546 kan itu emang ga pake s

110 ` if (config.online && keyword.includes(text))`

**Comment by ikkeh69** [comment]
makasih @Fahrineey546 dan @YogaSakti udah fix.

error line 101 sama 102 hapus huruf (s)
